name: "*** build Dopamine2-roothide.tipa ***"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
            fetch-depth: 0
            fetch-tags: true

      - name: Tags
        run: |
          set -x
          git fetch --tags https://github.com/roothide/Dopamine2-roothide
          git tag
          git log --first-parent --pretty=%d
          git describe --tags --abbrev=0
          
      - name: Install Procursus
        uses: dhinakg/procursus-action@main
        with:
          packages: ldid findutils sed coreutils make

      - name: Install THEOS
        run: |
          set -x
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          mkdir -p $THEOS
          curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos >> install-theos.sh
          gsed -E "/^\s*get_theos\s*$/,+1 s/^(\s*)(get_sdks)\s*$/\1mkdir -p \${THEOS}\/sdks\n\1touch \${THEOS}\/sdks\/sdk\n\1\2/g" -i install-theos.sh
          bash install-theos.sh
          curl -L https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz --output $THEOS/sdks/iPhoneOS16.5.sdk.tar.xz
          gunzip $THEOS/sdks/iPhoneOS16.5.sdk.tar.xz
          tar -xf $THEOS/sdks/iPhoneOS16.5.sdk.tar -C $THEOS/sdks
          rm $THEOS/sdks/iPhoneOS16.5.sdk.tar
          cd $BASEDIR

      - name: Build and Install trustcache
        run: |
          set -x
          git clone https://github.com/CRKatri/trustcache
          cd trustcache
          gmake -j$(sysctl -n hw.physicalcpu) OPENSSL=1
          sudo cp trustcache /opt/procursus/bin/

      - name: Set Environment Variables
        run: |
          set -x
          T2=$(TZ=UTC-2 date +'%Y%m%d_%H%M%S')
          TS=$(date -j -f "%Y%m%d_%H%M%S" "${T2}" +%s)
          SHASH=$(git rev-parse --short HEAD)
          echo "ctime=${T2}" >> $GITHUB_ENV
          echo "ctimestamp=${TS}" >> $GITHUB_ENV
          echo "shorthash=${SHASH}" >> $GITHUB_ENV

      - name: Install libarchive
        run: |
          brew install libarchive

      - name: Build
        run: |
          set -x
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          gmake -j$(sysctl -n hw.physicalcpu) NIGHTLY=1
          TAG=$(git describe --tags --abbrev=0)
          mv ./Application/Dopamine.tipa  "./Application/roothide-Dopamine2-${TAG}.tipa"
          echo "tag=${TAG}" >> $GITHUB_ENV

      - name: Upload Artifact
        id: dopamine-latest-upload
        uses: actions/upload-artifact@v3
        with:
          name: roothide-Dopamine2-${{ env.tag }}.tipa
          path: |
            ${{ github.workspace }}/Application/roothide-Dopamine2-${{ env.tag }}.tipa